import React,{useState,useEffect,useRef} from 'react';
import {View} from './LuxuryOffice';
import {DealDeskRecords,readAll,crmTables,emptySnapshot,recordLabel} from './DealDeskRecords';
import type {CrmSnapshot,CrmTable} from './DealDeskRecords';
const departments=[['acquisitions','Acquisitions Department','●','#10c99c'],['dispositions','Dispositions Department','●','#f4a511'],['operations','Operations Department','●','#25bcec'],['ceo','CEO / Approvals','●','#eabb18'],['conference','Deal Review','●','#b45cff']];
const tabs=['Desk Overview','SureCash Underwriting','Deal Pipeline','The Network','Weissman PC Escrow','CRM Records','Live DealDesk'];
const profiles:Record<string,{title:string;initials:string;description:string;work:string[];metrics:string[]}>={
 acquisitions:{title:'Acquisitions Specialist',initials:'AC',description:'Property discovery, closed-sale comparable research, and SureCash offer preparation across Metro Atlanta.',work:['Discover properties in Brookhaven, Buckhead, Sandy Springs and Dunwoody','Compare three qualifying closed sales and average their sale prices','Calculate renovation offers at 40% or new construction at 20–25% of ARV','Prepare proposed DealDesk records for CEO approval'],metrics:['Property research','Comparable sales','SureCash offers','Pending approvals']},
 dispositions:{title:'Dispositions Specialist',initials:'DI',description:'Matching opportunities with verified buyers and researching builders for The Network.',work:['Compare DealDesk opportunities with documented buyer buy boxes','Rank geographical, strategy and budget fit','Research developers behind newly built homes','Submit new buyer profiles for CEO approval'],metrics:['Verified buyers','Buyer matches','Developer prospects','Pending approvals']},
 operations:{title:'Operations Specialist',initials:'OP',description:'Activity monitoring, transaction deadlines, document tracking and executive reporting.',work:['Track department tasks, errors and approval requests','Prepare hourly reports during business hours','Monitor recorded due diligence and closing deadlines','Escalate missing documents and critical risks'],metrics:['Active transactions','Upcoming deadlines','Hourly reports','Critical alerts']},
 ceo:{title:'Managing Principal & CEO',initials:'AZ',description:'Ashari Zakar · Executive oversight and final approval authority.',work:['Review sourced evidence and offer calculations','Approve exact proposed DealDesk changes','Review department reports and blockers','Authorize consequential communications and commitments'],metrics:['Pending decisions','Department reports','Activity history','Transaction results']},
 conference:{title:'Deal Review Committee',initials:'IC',description:'Collaborative review of opportunities, supporting evidence and next actions.',work:['Review qualifying comps and property characteristics','Inspect SureCash calculations','Evaluate buyer matching evidence','Review document and deadline handoffs'],metrics:['Deals under review','Comp evidence','Buyer criteria','Next actions']}
};
const money=(v:number)=>v.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
export function WorkstationDashboard({room,onRoom,onClose,onFocus}:{room:View|null;onRoom:(v:View)=>void;onClose:()=>void;onFocus:(v:View)=>void}){
 const [tab,setTab]=useState(tabs[0]);const [arv,setArv]=useState(1850000);const [strategy,setStrategy]=useState('Teardown');const [percent,setPercent]=useState(20);const [query,setQuery]=useState('');const [filter,setFilter]=useState('All');
 const [password,setPassword]=useState('');const [authenticated,setAuthenticated]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [snapshot,setSnapshot]=useState<CrmSnapshot>(emptySnapshot);const [errors,setErrors]=useState<Partial<Record<CrmTable,string>>>({});const [updated,setUpdated]=useState('');const request=useRef<AbortController|null>(null);const sessionChecked=useRef(false);
 function disconnect(){void fetch('/api/dealdesk',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})});request.current?.abort();setAuthenticated(false);setPassword('');setSnapshot(emptySnapshot());setErrors({});setError('');setBusy(false);setUpdated('');}
 useEffect(()=>{if(room){setTab(tabs[0]);if(!sessionChecked.current){sessionChecked.current=true;void connect(true);}}},[room]);
 useEffect(()=>()=>request.current?.abort(),[]);
 async function connect(silent=false){
  request.current?.abort();const controller=new AbortController();request.current=controller;setBusy(true);setError('');
  try {
   const deals=await readAll('Deals',password,controller.signal);
   if(controller.signal.aborted)return;
   const next=emptySnapshot();next.Deals=deals;const failures:Partial<Record<CrmTable,string>>={};
   await Promise.all(crmTables.filter(t=>t!=='Deals').map(async table=>{try{next[table]=await readAll(table,password,controller.signal);}catch(e){if(!controller.signal.aborted)failures[table]=e instanceof Error?e.message:'Read failed.';}}));
   if(controller.signal.aborted)return;
   setSnapshot(next);setErrors(failures);setAuthenticated(true);setPassword('');setUpdated(new Date().toLocaleString());
  }catch(e){if(!controller.signal.aborted&&!silent)setError(e instanceof Error?e.message:'Connection failed.');}
  finally{if(!controller.signal.aborted)setBusy(false);}
 }
 if(!authenticated)return <div className="wd-login"><button className="wd-login-close" onClick={onClose} aria-label="Close workstation">×</button><img src="/brand/emblem.png" alt="AZRE"/><span className="eyebrow">PRIVATE HEADQUARTERS</span><h2>Welcome to DealDesk</h2><p>Sign in to review your company’s deals, buyers, contacts and tasks.</p><form className="wd-inputs" onSubmit={e=>{e.preventDefault();void connect();}}><label>Office access password<input autoFocus type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required disabled={busy}/></label><button className="wd-launch" disabled={busy}>{busy?'Connecting to DealDesk…':'Sign in to dashboard'}</button></form>{error&&<p role="alert" className="wd-login-error">{error}</p>}<small>Sign in once for up to eight hours across all workstation screens. Use your office access password (at least 8 characters). Your DealDesk account password is used only inside Live DealDesk.</small></div>;
 const profile=profiles[room||'acquisitions']||profiles.acquisitions;const rate=strategy==='Renovation'?40:percent;const offer=arv*rate/100;
 return <>
 <header className="wd-header"><img src="/brand/emblem.png" alt="AZRE"/><div><strong>ASHARI <em>ZAKAR</em> <span>│ REAL ESTATE │ DEALDESK ULTRA</span></strong><p>Headquarters workstation · <a href="https://dealdesk.asharizakargroup.com" target="_blank" rel="noopener noreferrer">dealdesk.asharizakargroup.com ↗</a></p></div><button className="wd-launch" onClick={()=>setTab('Live DealDesk')}>Launch DealDesk Ultra ↗</button><button aria-label="Close workstation" onClick={onClose}>×</button></header>
 <div className="wd-nav"><nav aria-label="Workstation departments">{departments.map(([id,label,dot,color])=><button key={id} aria-pressed={room===id} onClick={()=>onRoom(id as View)}><i style={{color}}>{dot}</i>{label}</button>)}</nav><nav aria-label="Dashboard sections">{tabs.map(t=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t}</button>)}</nav></div>
 <main className="wd-body" hidden={tab==='Live DealDesk'}>{tab==='CRM Records'&&<DealDeskRecords snapshot={snapshot} errors={errors}/>}<div className="wd-notice" hidden={tab==='CRM Records'}>DealDesk read-only snapshot · Updated {updated} · AI workflows are not running. {Object.keys(errors).length>0&&'Some record types could not be loaded; see CRM Records.'}</div>
 {tab==='Desk Overview'&&<><section className="wd-profile"><b>{profile.initials}</b><div><h2>{profile.title}</h2><p>{profile.description}</p><small>AZRE operating workflow · Metro Atlanta</small></div><button onClick={()=>onFocus(room||'acquisitions')}>Focus 3D Camera On Desk</button></section><div className="wd-metrics">{crmTables.map(t=><section key={t}><p>{t==='PluginTasks'?'CRM Tasks':t}</p><strong>{errors[t]?'Unavailable':snapshot[t].length.toLocaleString()}</strong><small>{errors[t]?'Read failed':'Records loaded from DealDesk'}</small></section>)}</div><div className="wd-columns"><section><h3>◷ SPECIALIST WORKFLOWS <small>Planned</small></h3>{profile.work.map(w=><p className="wd-work" key={w}><span>○</span>{w}</p>)}</section><section><h3>♧ THE SURECASH OFFER STANDARD TERMS</h3>{[['Purchase condition','As-is'],['Earnest money deposit','1% of agreed purchase price'],['Due diligence','7 calendar days'],['Closing timeline','Approximately 30 days'],['Preferred closing counsel','Weissman PC']].map(([k,v])=><div className="wd-row" key={k}><span>{k}</span><b>{v}</b></div>)}<small>Proposed standard terms; executed agreements control.</small></section></div></>}
 {tab==='SureCash Underwriting'&&<section><h2>SureCash ARV Underwriting Model</h2><p>Average the actual sale prices of three qualifying closed sales. Apply the approved percentage formula.</p><div className="wd-columns"><div className="wd-inputs"><label>Investment strategy<select value={strategy} onChange={e=>setStrategy(e.target.value)}><option>Teardown</option><option>Renovation</option></select></label><label>Supported ARV <strong>{money(arv)}</strong><input aria-label="Supported ARV" type="range" min="100000" max="5000000" step="10000" value={arv} onChange={e=>setArv(+e.target.value)}/><input aria-label="ARV amount" type="number" min="0" value={arv} onChange={e=>setArv(Math.max(0,+e.target.value))}/></label>{strategy==='Teardown'&&<label>Offer percentage: {percent}%<input aria-label="Offer percentage" type="range" min="20" max="25" step=".5" value={percent} onChange={e=>setPercent(+e.target.value)}/></label>}<p>{strategy==='Teardown'?'Use the three largest qualifying detached spec infill closed sales within one mile.':'Use three highest-priced qualifying renovated/pristine closed sales, matching beds, baths and approximately ±300 square feet within one mile.'}</p></div><section className="wd-result"><h3>OFFER CALCULATION</h3><div className="wd-row"><span>Supported ARV</span><b>{money(arv)}</b></div><div className="wd-row"><span>Acquisition percentage</span><b>{rate}%</b></div><p>SURECASH OFFER TARGET</p><strong>{money(offer)}</strong><p>1% proposed EMD: {money(offer*.01)}</p><small>No cost deductions. Net profit is not calculated. This calculator does not submit offers or save CRM records.</small></section></div></section>}
 {tab==='Deal Pipeline'&&<section><h2>Deal Pipeline</h2><p>{snapshot.Deals.length} DealDesk opportunities · Expand a property for supporting information.</p><div className="wd-filters">{['All',...Array.from(new Set(snapshot.Deals.map(r=>String(r.subMarket||'')).filter(Boolean)))].map(f=><button key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}</button>)}<input aria-label="Search deals" placeholder="Search address, submarket…" value={query} onChange={e=>setQuery(e.target.value)}/></div>{snapshot.Deals.filter(r=>(filter==='All'||r.subMarket===filter)&&JSON.stringify(r).toLowerCase().includes(query.toLowerCase())).map((r,i)=><details className="wd-record" key={String(r.id||i)}><summary>{recordLabel(r)} <small>{String(r.offerDecision||r.status||'')}</small></summary><div className="wd-metrics">{['listPrice','offerPrice','renovationARV','newConstructionARV'].map(k=><section key={k}><p>{k}</p><strong>{typeof r[k]==='number'?money(r[k] as number):'Not recorded'}</strong></section>)}</div><pre>{JSON.stringify(r,null,2)}</pre></details>)}</section>}
 {tab==='The Network'&&<section><h2>The Network · Buyer Directory</h2><p>Buyer status and criteria as recorded in DealDesk.</p>{errors.Buyers&&<p role="alert">{errors.Buyers}</p>}<input aria-label="Search buyers" placeholder="Search buyer, company, buy box…" value={query} onChange={e=>setQuery(e.target.value)}/><div className="wd-columns">{snapshot.Buyers.filter(r=>JSON.stringify(r).toLowerCase().includes(query.toLowerCase())).map((r,i)=><section key={String(r.id||i)}><h3>{recordLabel(r)}</h3><p>{String(r.companyName||'')} · {String(r.status||'Status not recorded')}</p><p>{String(r.email||'')} {String(r.phone||'')}</p><h4>Buy box</h4><pre>{r.buyBox?JSON.stringify(r.buyBox,null,2):'Not recorded'}</pre><details><summary>All buyer information</summary><pre>{JSON.stringify(r,null,2)}</pre></details></section>)}</div></section>}
 {tab==='Weissman PC Escrow'&&<section><h2>Operations · Documents & Deadlines</h2><p>Contract dates and CRM tasks. No escrow bank balances are connected.</p>{snapshot.Deals.filter(r=>r.inspectionDate||r.emdDate||r.underContractDate||r.closedDate||r.nextFollowUpDate).map((r,i)=><section key={String(r.id||i)}><h3>{recordLabel(r)}</h3>{['inspectionDate','emdDate','underContractDate','closedDate','nextFollowUpDate'].filter(k=>r[k]).map(k=><div className="wd-row" key={k}><span>{k}</span><b>{String(r[k])}</b></div>)}</section>)}<h3>CRM Tasks ({snapshot.PluginTasks.length})</h3>{errors.PluginTasks&&<p role="alert">{errors.PluginTasks}</p>}{snapshot.PluginTasks.map((r,i)=><details className="wd-record" key={String(r.id||i)}><summary>{recordLabel(r)} · {String(r.status||'')} · {String(r.dueDate||'')}</summary><pre>{JSON.stringify(r,null,2)}</pre></details>)}</section>}
 </main>
 <div className="wd-live" hidden={tab!=='Live DealDesk'}><iframe src="https://dealdesk.asharizakargroup.com" title="Live DealDesk session" allow="clipboard-write"/><p>Sign in directly to DealDesk. <a href="https://dealdesk.asharizakargroup.com" target="_blank" rel="noopener noreferrer">Open in a new tab ↗</a> if embedded authentication is blocked.</p></div>
 <footer className="wd-footer"><span>● Read-only DealDesk · Updated {updated}</span><button disabled={busy} onClick={()=>void connect()}>{busy?'Refreshing…':'Refresh data'}</button><button onClick={disconnect}>Sign out</button><button onClick={onClose}>Return to 3D Office</button></footer>
 </>;
}
